name: housebarber
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  syncfusion_flutter_calendar: ^21.2.3
  sqflite: ^2.2.8+4
  path: ^1.8.2
  url_launcher: ^6.1.11
  multi_select_flutter: ^4.0.0
  flutter_colorpicker: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets\images.jpg
    - assets\LogoHouseBarber.png
